version: '3.8'
services:
  frps:
    image: yuanjua/frps:latest
    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - ./frps.toml:/frp/frps.toml
    environment:
      - TZ=Asia/Shanghai