version: '3.8'
services:
  frpc:
    image: yuanjua/frpc:latest
    container_name: frpc
    restart: always
    network_mode: host
    volumes:
      - ./frpc.toml:/frp/frpc.toml
    environment:
      - TZ=Asia/Shanghai